### ISSUE TITLE
Width to big

### ISSUE THREAD

**Issue by MonkeyAndres** [devfreebooks/devfreebooks.github.io#29]
The width in the page is to big. Solve it added:

```css

html{
    overflow-x: hidden;
}

```
